# Generated by Django 6.0.4 on 2026-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_number", models.CharField(db_index=True, max_length=50)),
                ("injury", models.CharField(default="Assessment", max_length=200)),
                ("body_part", models.CharField(default="Unknown", max_length=100)),
                ("treatment", models.CharField(blank=True, default="", max_length=500)),
                ("details", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("confirmed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Medical Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
